<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <PackageId>Entity.Http.Rpc</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Title>Entity.Http.Rpc</Title>
        <Authors>Lleoliad</Authors>
        <Owners>Lleoliad</Owners>
        <PackageOutputPath>../../nupkg</PackageOutputPath>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <Description>HTTP RPC support package for the Entity server framework, providing modular service communication and reusable integration infrastructure for .NET.</Description>
        <Copyright>Copyright 2026 Lleoliad</Copyright>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageIcon>icon.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageReleaseNotes>Initial release of Entity.Http.Rpc with HTTP RPC support infrastructure for the Entity server framework.</PackageReleaseNotes>
        <PackageProjectUrl>https://github.com/lleoliad/Entity.Http.Rpc</PackageProjectUrl>
        <RepositoryUrl>https://github.com/lleoliad/Entity.Http.Rpc</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>Entity;HTTP;RPC;Networking;.NET</PackageTags>
        <AssemblyName>Entity.Http.Rpc</AssemblyName>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <RootNamespace>Entities.Http.Rpc</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <IsPackable>true</IsPackable>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <SignAssembly>true</SignAssembly>
<!--        <IncludeSymbols>true</IncludeSymbols>-->
<!--        <SymbolPackageFormat>snupkg</SymbolPackageFormat>-->
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\..\Entity\Entity.csproj"/>
    </ItemGroup>
    
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.26" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.17.0" />
    </ItemGroup>
    
    <ItemGroup>
        <!-- package metadata file -->
        <None Include="LICENSE" Pack="true" PackagePath="\" />
        <None Include="README.md" Pack="true" PackagePath="\" />
        <None Include="Assets/icon.png" Pack="true" PackagePath="\" Link="icon.png" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Tests\**\*.cs" />
        <EmbeddedResource Remove="Tests\**\*" />
        <None Remove="Tests\**\*" />
    </ItemGroup>
</Project>
